# pythonpath = '/home/alice/HH-Tula/headhunter/headhunter'
# command = '/home/alice/HH-Tula/venv/bin/gunicorn'
# wsgi_app = "/home/alice/HH-Tula/headhunter/headhunter"
# timeout = "120"
# graceful_timeout = "50"
# keepalive = "5"
# bind = "127.0.0.1:8001"
# workers = "3"
# threads = "8"
# loglevel = 'debug'
# user = "alice"
# worker_class = "gevent"
# max_requests = 1000
# raw_env = "DJANGO_SETTINGS_MODULE=headhunter.settings"
